In [1]:
using OnePiece

using KernelDensity

## get_entropy

In [2]:
OnePiece.information.get_entropy(zeros(10))

10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [3]:
OnePiece.information.get_entropy(ones(10))

10-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

## get_signal_to_noise_ratio

In [4]:
for (te1, te2) in [
    (collect(1:3), collect(10:10:30)),
    (zeros(3), zeros(3)),
    (ones(3), [0.001, 0.001, 0.001]),
    ([0.001, 0.001, 0.001], ones(3)),
    ([0.001, 0.001, 0.001], [10, 10, 10]),
]

    println(OnePiece.information.get_signal_to_noise_ratio(te1, te2))

end

-1.6363636363636365
0.0
4.990009990009989
-4.990009990009989
-4.999000099990002


## get_*

In [5]:
function call_all(te1, te2, te)

    vcat(
        [
            fu(te1, te2) for fu in [
                OnePiece.information.get_kolmogorov_smirnov_statistic,
                OnePiece.information.get_kullback_leibler_divergence,
                OnePiece.information.get_thermodynamic_breadth,
                OnePiece.information.get_thermodynamic_depth,
            ]
        ],
        [
            fu(te1, te2, te) for fu in [
                OnePiece.information.get_symmetric_kullback_leibler_divergence,
                OnePiece.information.get_antisymmetric_kullback_leibler_divergence,
            ]
        ],
    )

end

call_all (generic function with 1 method)

In [6]:
name_ = [
    "kolmogorov_smirnov_statistic",
    "kullback_leibler_divergence",
    "thermodynamic_breadth",
    "thermodynamic_depth",
    "symmetric_kullback_leibler_divergence",
    "antisymmetric_kullback_leibler_divergence",
]

6-element Vector{String}:
 "kolmogorov_smirnov_statistic"
 "kullback_leibler_divergence"
 "thermodynamic_breadth"
 "thermodynamic_depth"
 "symmetric_kullback_leibler_divergence"
 "antisymmetric_kullback_leibler_divergence"

In [7]:
for (te1, te2) in [([1, 1, 1], [1, 1, 1]), ([1, 2, 3], [10, 20, 30])]

    te = 0.2 * te1 + 0.8 * te2

    OnePiece.figure.plot_scatter([te1, te2])

    OnePiece.figure.plot_scatter(call_all(te1, te2, te); name_ = name_)

end

Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-7-13_16:50:25.777.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-7-13_16:50:26.871.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-7-13_16:50:26.881.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-7-13_16:50:26.893.html.


In [8]:
n_po = 100

te1 = OnePiece.vector_number.shift_minimum(randn(n_po), "0<")

ve1s = te1 .+ 1

te2 = OnePiece.vector_number.shift_minimum(randn(n_po), "0<")

100-element Vector{Float64}:
 4.16619537272334
 3.1492129340009796
 2.6306170479952384
 0.010172547202516924
 4.015326394373842
 3.6485862150206407
 2.420379194004388
 3.2313142929667458
 3.83427911479383
 3.7720446515554924
 2.8914652850671305
 4.3381130927695795
 4.3123105291217065
 ⋮
 2.8200692288126064
 4.529749194907678
 5.116106487072885
 3.6195751619764027
 3.9985047854908737
 4.929585117839126
 5.0354151311711615
 3.867381517150265
 3.1555522650336156
 3.1511617091846404
 4.045438605990354
 3.6667680578032193

In [9]:
for (te1, te2) in [(te1, te1), (te1, ve1s), (te1, te2)]

    un1 = kde(te1)

    un2 = kde(te2)

    de1 = un1.density

    de2 = un2.density

    de3 = 0.2 * de1 + 0.8 * de2

    OnePiece.figure.plot_scatter(
        [de1, de2],
        [collect(un1.x), collect(un2.x)];
        layout = Dict("yaxis" => Dict("title" => "Density"), "xaxis" => Dict("title" => "Grid")),
    )

    OnePiece.figure.plot_scatter(call_all(de1, de2, de3); name_ = name_)

end

Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-7-13_16:50:28.748.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-7-13_16:50:29.295.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-7-13_16:50:29.325.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-7-13_16:50:29.341.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-7-13_16:50:29.36.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-7-13_16:50:29.415.html.


## get_mutual_information

## get_information_coefficient

In [10]:
te1 = collect(0:10)

te2 = collect(0:10:100)

bi = kde((te1, te2), npoints = (8, 8))

y = collect(bi.y)

x = collect(bi.x)

z = bi.density

OnePiece.figure.plot_heat_map(z, y, x)

Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-7-13_16:50:30.632.html.


Process(`open /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-7-13_16:50:30.632.html`, ProcessRunning)