In [1]:
using OnePiece

---

In [2]:
using KernelDensity

## get_entropy

In [3]:
OnePiece.information.get_entropy(zeros(10))

10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [4]:
OnePiece.information.get_entropy(ones(10))

10-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

## get_signal_to_noise_ratio

In [5]:
for (te1, te2) in [
    (collect(1:3), collect(10:10:30)),
    (zeros(3), zeros(3)),
    (ones(3), [0.001, 0.001, 0.001]),
    ([0.001, 0.001, 0.001], ones(3)),
    ([0.001, 0.001, 0.001], [10, 10, 10]),
]

    println(OnePiece.information.get_signal_to_noise_ratio(te1, te2))

end

-1.6363636363636365
0.0
4.990009990009989
-4.990009990009989
-4.999000099990002


## get_*

In [6]:
function call_all(te1, te2, te)

    vcat(
        [
            fu(te1, te2) for fu in [
                OnePiece.information.get_kolmogorov_smirnov_statistic,
                OnePiece.information.get_kullback_leibler_divergence,
                OnePiece.information.get_thermodynamic_breadth,
                OnePiece.information.get_thermodynamic_depth,
            ]
        ],
        [
            fu(te1, te2, te) for fu in [
                OnePiece.information.get_symmetric_kullback_leibler_divergence,
                OnePiece.information.get_antisymmetric_kullback_leibler_divergence,
            ]
        ],
    )

end

call_all (generic function with 1 method)

In [7]:
name_ = [
    "kolmogorov_smirnov_statistic",
    "kullback_leibler_divergence",
    "thermodynamic_breadth",
    "thermodynamic_depth",
    "symmetric_kullback_leibler_divergence",
    "antisymmetric_kullback_leibler_divergence",
]

6-element Vector{String}:
 "kolmogorov_smirnov_statistic"
 "kullback_leibler_divergence"
 "thermodynamic_breadth"
 "thermodynamic_depth"
 "symmetric_kullback_leibler_divergence"
 "antisymmetric_kullback_leibler_divergence"

In [8]:
for (te1, te2) in [([1, 1, 1], [1, 1, 1]), ([1, 2, 3], [10, 20, 30])]

    te = 0.2 * te1 + 0.8 * te2

    OnePiece.figure.plot_x_y([te1, te2])

    OnePiece.figure.plot_x_y(call_all(te1, te2, te); name_ = name_)

end

Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/2022-7-10_14:22:31.096.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/2022-7-10_14:22:32.012.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/2022-7-10_14:22:32.021.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/2022-7-10_14:22:32.031.html.


In [9]:
n_po = 100

te1 = OnePiece.tensor.shift_minimum(randn(n_po), "0<")

ve1s = te1 .+ 1

te2 = OnePiece.tensor.shift_minimum(randn(n_po), "0<")

100-element Vector{Float64}:
 1.2375268394421726
 2.5929599992775194
 1.3949519300803537
 2.108495913055538
 1.9851603207397925
 1.4666499315659423
 3.8459893191601484
 1.8780392127685326
 4.181260986497925
 2.708398493644403
 3.2168746669891517
 3.390775606645857
 1.9100474561361618
 ⋮
 1.9596653485585986
 1.7868177339446831
 3.860648921240694
 2.097100442473404
 3.0646086246825175
 3.3210056172796305
 2.653627978578959
 1.9122834143244158
 2.9004380284014157
 1.5619003948196948
 1.1458117501957217
 3.6279021764963826

In [10]:
for (te1, te2) in [(te1, te1), (te1, ve1s), (te1, te2)]

    un1 = kde(te1)

    un2 = kde(te2)

    de1 = un1.density

    de2 = un2.density

    de3 = 0.2 * de1 + 0.8 * de2

    OnePiece.figure.plot_x_y(
        [de1, de2],
        [collect(un1.x), collect(un2.x)];
        la = Dict("yaxis" => Dict("title" => "Density"), "xaxis" => Dict("title" => "Grid")),
    )

    OnePiece.figure.plot_x_y(call_all(de1, de2, de3); name_ = name_)

end

Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/2022-7-10_14:22:33.709.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/2022-7-10_14:22:34.11.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/2022-7-10_14:22:34.165.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/2022-7-10_14:22:34.175.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/2022-7-10_14:22:34.192.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/2022-7-10_14:22:34.205.html.


## get_mutual_information

## get_information_coefficient

In [11]:
te1 = collect(0:10)

te2 = collect(0:10:100)

bi = kde((te1, te2), npoints = (8, 8))

y = collect(bi.y)

x = collect(bi.x)

z = bi.density

OnePiece.figure.plot_heat_map(z, y, x)

Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/2022-7-10_14:22:35.55.html.


Process(`open /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/2022-7-10_14:22:35.55.html`, ProcessRunning)

---