In [1]:
using Revise
using OnePiece

## get_entropy

In [2]:
OnePiece.information.get_entropy(zeros(10))

10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [3]:
OnePiece.information.get_entropy(ones(10))

10-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

## get_signal_to_noise_ratio

In [4]:
for (te1, te2) in [
    (collect(1:3), collect(10:10:30)),
    (zeros(3), zeros(3)),
    (ones(3), [0.001, 0.001, 0.001]),
    ([0.001, 0.001, 0.001], ones(3)),
    ([0.001, 0.001, 0.001], [10, 10, 10]),
]

    println(OnePiece.information.get_signal_to_noise_ratio(te1, te2))

end

-1.6363636363636365
0.0
4.990009990009989
-4.990009990009989
-4.999000099990002


## get_*

In [5]:
function call_all(te1, te2, te)

    vcat(
        [
            fu(te1, te2) for fu in [
                OnePiece.information.get_kolmogorov_smirnov_statistic,
                OnePiece.information.get_kullback_leibler_divergence,
                OnePiece.information.get_thermodynamic_breadth,
                OnePiece.information.get_thermodynamic_depth,
            ]
        ],
        [
            fu(te1, te2, te) for fu in [
                OnePiece.information.get_jensen_shannon_divergence,
                OnePiece.information.get_kwat_pablo_divergence,
            ]
        ],
    )

end

call_all (generic function with 1 method)

In [6]:
name_ = [
    "kolmogorov_smirnov_statistic",
    "kullback_leibler_divergence",
    "thermodynamic_breadth",
    "thermodynamic_depth",
    "jensen_shannon_divergence",
    "kwat_pablo_divergence",
]

for (te1, te2) in [([1, 1, 1], [1, 1, 1]), ([1, 2, 3], [10, 20, 30])]

    te = 0.2 * te1 + 0.8 * te2

    OnePiece.figure.plot_x_y([te1, te2])

    OnePiece.figure.plot_x_y(call_all(te1, te2, te); name_ = name_)

end

Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.


In [7]:
n_po = 100

te1 = OnePiece.tensor.shift_minimum(randn(n_po), "0<")

ve1s = te1 .+ 1

te2 = OnePiece.tensor.shift_minimum(randn(n_po), "0<")

100-element Vector{Float64}:
 1.5101027448015474
 0.5225229471959401
 1.6777619505744548
 0.7558534499597593
 2.2650066055561617
 2.5555447543175918
 3.0951981648679165
 2.4341311079413948
 1.7356504895798854
 2.3414240700913753
 2.419986896485173
 2.2898544791209208
 1.258792039381768
 ⋮
 3.299072715699078
 0.9030707030271505
 2.8399871602892617
 2.432701557285698
 4.4836128883569515
 1.7957655809112452
 1.6830203870536817
 3.3696873310310784
 2.8966783369713576
 2.9591180005994224
 3.237053074117466
 1.403066916101864

In [8]:
using KernelDensity

In [9]:
for (te1, te2) in [(te1, te1), (te1, ve1s), (te1, te2)]

    un1 = kde(te1)

    un2 = kde(te2)

    de1 = un1.density

    de2 = un2.density

    de3 = 0.2 * de1 + 0.8 * de2

    OnePiece.figure.plot_x_y(
        [de1, de2],
        [collect(un1.x), collect(un2.x)];
        la = Dict("yaxis" => Dict("title" => "Density"), "xaxis" => Dict("title" => "Grid")),
    )

    OnePiece.figure.plot_x_y(call_all(de1, de2, de3); name_ = name_)

end

Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.


## get_information_coefficient

In [10]:
te1 = collect(0:10)

te2 = collect(0:10:100)

bi = kde((te1, te2), npoints = (8, 8))

y = collect(bi.y)

x = collect(bi.x)

z = bi.density

OnePiece.figure.plot_heat_map(z, y, x)

Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.


"/Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html"