In [1]:
using Revise
using OnePiece

## get_entropy

In [2]:
OnePiece.information.get_entropy(zeros(10))

10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [3]:
OnePiece.information.get_entropy(ones(10))

10-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

## get_signal_to_noise_ratio

In [4]:
for (te1, te2) in [
    (collect(1:3), collect(10:10:30)),
    (zeros(3), zeros(3)),
    (ones(3), [0.001, 0.001, 0.001]),
    ([0.001, 0.001, 0.001], ones(3)),
    ([0.001, 0.001, 0.001], [10, 10, 10]),
]

    println(OnePiece.information.get_signal_to_noise_ratio(te1, te2))

end

-1.6363636363636365
0.0
4.990009990009989
-4.990009990009989
-4.999000099990002


## get_*

In [5]:
function call_all(te1, te2, te)

    vcat(
        [
            fu(te1, te2) for fu in [
                OnePiece.information.get_kolmogorov_smirnov_statistic,
                OnePiece.information.get_kullback_leibler_divergence,
                OnePiece.information.get_thermodynamic_breadth,
                OnePiece.information.get_thermodynamic_depth,
            ]
        ],
        [
            fu(te1, te2, te) for fu in [
                OnePiece.information.get_jensen_shannon_divergence,
                OnePiece.information.get_kwat_pablo_divergence,
            ]
        ],
    )

end

call_all (generic function with 1 method)

In [6]:
name_ = [
    "kolmogorov_smirnov_statistic",
    "kullback_leibler_divergence",
    "thermodynamic_breadth",
    "thermodynamic_depth",
    "jensen_shannon_divergence",
    "kwat_pablo_divergence",
]

for (te1, te2) in [([1, 1, 1], [1, 1, 1]), ([1, 2, 3], [10, 20, 30])]

    te = 0.2 * te1 + 0.8 * te2

    OnePiece.figure.plot_x_y([te1, te2])

    OnePiece.figure.plot_x_y(call_all(te1, te2, te); name_ = name_)

end

Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.


In [7]:
n_po = 100

te1 = OnePiece.tensor.shift_minimum(randn(n_po), "0<")

ve1s = te1 .+ 1

te2 = OnePiece.tensor.shift_minimum(randn(n_po), "0<")

100-element Vector{Float64}:
 1.4390056853984214
 0.36454129437370275
 2.554858552340219
 0.7093840336522523
 2.2541406103833594
 2.903260442150564
 1.1650887947886333
 2.1406319022183897
 3.3062717007682374
 2.535406423262892
 4.575526323430835
 0.45332363430348055
 1.738711837572514
 ⋮
 3.941341789905393
 3.7744976539023485
 1.4621004064939063
 2.7078291668711643
 3.6890346349178857
 2.9891666551482143
 3.0943130876437848
 3.7898058967500017
 2.9370507039572824
 0.041834808496024056
 1.4706814896667741
 2.664090678157458

In [8]:
using KernelDensity

In [9]:
for (te1, te2) in [(te1, te1), (te1, ve1s), (te1, te2)]

    un1 = kde(te1)

    un2 = kde(te2)

    de1 = un1.density

    de2 = un2.density

    de3 = 0.2 * de1 + 0.8 * de2

    OnePiece.figure.plot_x_y(
        [de1, de2],
        [collect(un1.x), collect(un2.x)];
        la = Dict("yaxis" => Dict("title" => "Density"), "xaxis" => Dict("title" => "Grid")),
    )

    OnePiece.figure.plot_x_y(call_all(de1, de2, de3); name_ = name_)

end

Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.


## get_information_coefficient

In [10]:
te1 = collect(0:10)

te2 = collect(0:10:100)

bi = kde((te1, te2), npoints = (8, 8))

y = collect(bi.y)

x = collect(bi.x)

z = bi.density

OnePiece.figure.plot_heat_map(z, y, x)

Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.


"/Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html"