In [1]:
using Revise
using OnePiece

## get_entropy

In [2]:
OnePiece.information.get_entropy(zeros(10))

10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [3]:
OnePiece.information.get_entropy(ones(10))

10-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

## get_signal_to_noise_ratio

In [4]:
for (te1, te2) in [
    (collect(1:3), collect(10:10:30)),
    (zeros(3), zeros(3)),
    (ones(3), [0.001, 0.001, 0.001]),
    ([0.001, 0.001, 0.001], ones(3)),
    ([0.001, 0.001, 0.001], [10, 10, 10]),
]

    println(OnePiece.information.get_signal_to_noise_ratio(te1, te2))

end

-1.6363636363636365
0.0
4.990009990009989
-4.990009990009989
-4.999000099990002


## get_*

In [5]:
function call_all(te1, te2, te)

    vcat(
        [
            fu(te1, te2) for fu in [
                OnePiece.information.get_kolmogorov_smirnov_statistic,
                OnePiece.information.get_kullback_leibler_divergence,
                OnePiece.information.get_thermodynamic_breadth,
                OnePiece.information.get_thermodynamic_depth,
            ]
        ],
        [
            fu(te1, te2, te) for fu in [
                OnePiece.information.get_jensen_shannon_divergence,
                OnePiece.information.get_kwat_pablo_divergence,
            ]
        ],
    )

end

call_all (generic function with 1 method)

In [6]:
name_ = [
    "kolmogorov_smirnov_statistic",
    "kullback_leibler_divergence",
    "thermodynamic_breadth",
    "thermodynamic_depth",
    "jensen_shannon_divergence",
    "kwat_pablo_divergence",
]

for (te1, te2) in [([1, 1, 1], [1, 1, 1]), ([1, 2, 3], [10, 20, 30])]

    te = 0.2 * te1 + 0.8 * te2

    OnePiece.figure.plot_x_y([te1, te2])

    OnePiece.figure.plot_x_y(call_all(te1, te2, te); name_ = name_)

end

Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.


In [7]:
n_po = 100

te1 = OnePiece.tensor.shift_minimum(randn(n_po), "0<")

ve1s = te1 .+ 1

te2 = OnePiece.tensor.shift_minimum(randn(n_po), "0<")

100-element Vector{Float64}:
 3.858459836396906
 2.3078018881027154
 2.633348189772414
 2.277344782057855
 3.388788360134048
 2.733929890877595
 5.7371727215556
 3.0568060155553365
 4.200662197840619
 1.515462741940597
 2.4270878895189396
 4.8204363734526305
 3.2100435714748903
 ⋮
 4.320833043905565
 2.5118335647093115
 4.852807616846979
 2.8444743151934215
 3.492188193555004
 1.7870811799191713
 4.624574571362881
 3.9440062986350872
 3.1704858240392926
 2.4185136370708453
 2.7283436071767544
 3.8066776427935984

In [8]:
using KernelDensity

In [9]:
for (te1, te2) in [(te1, te1), (te1, ve1s), (te1, te2)]

    un1 = kde(te1)

    un2 = kde(te2)

    de1 = un1.density

    de2 = un2.density

    de3 = 0.2 * de1 + 0.8 * de2

    OnePiece.figure.plot_x_y(
        [de1, de2],
        [collect(un1.x), collect(un2.x)];
        la = Dict("yaxis" => Dict("title" => "Density"), "xaxis" => Dict("title" => "Grid")),
    )

    OnePiece.figure.plot_x_y(call_all(de1, de2, de3); name_ = name_)

end

Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.
Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.


## get_information_coefficient

In [10]:
te1 = collect(0:10)

te2 = collect(0:10:100)

bi = kde((te1, te2), npoints = (8, 8))

y = collect(bi.y)

x = collect(bi.x)

z = bi.density

OnePiece.figure.plot_heat_map(z, y, x)

Made /Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html.


"/Users/kwat/.julia/scratchspaces/1fe83854-81c0-42f7-afc9-71ba9af673ca/OnePiece.html/scratch.html"